substitutions:
  _PROJECT_ID: gitops-vittal
steps: 
  - name: alpine
    args:
      - '-c'
      - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"
    id: branch name
    entrypoint: sh
    
  - name: alpine
    args:
      - '-c'
      - |
        echo "******************************"
        echo "******* Prepare SA key *******"
        echo "******************************"
        echo "$$GITOPS_SA_KEY" > sa.json
    id: prepare sa key
    entrypoint: sh
    secretEnv: ['GITOPS_SA_KEY']
    
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash' 
    args:
    - '-c'
    - |
        sh scripts/connect_mgcpHostcluster.sh
        
  - name: 'gcr.io/$_PROJECT_ID/envsubst'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        sh scripts/prepare_cluster_yml.sh
        echo "GKE cluster YML prepared."
      
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
    - '-c'
    - |    
        kubectl apply -f templates/cluster.yml
        echo "Customer GKE cluster provisioned."
      
timeout: 1000s     
options:
  logging: CLOUD_LOGGING_ONLY
  
availableSecrets:
  secretManager:
  - versionName: projects/1079862105808/secrets/gitops-solution/versions/latest
    env: 'GITOPS_SA_KEY'
        
