substitutions:
  _PROJECT_ID: gitops-vittal
steps:      
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash' 
    args:
    - '-c'
    - |
        sh scripts/connect_mgcpHostcluster.sh
        
  - name: 'gcr.io/$_PROJECT_ID/envsubst:latest'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        sh scripts/prepare_cluster_yml.sh
        echo "GKE cluster YML prepared.."
      
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
    - '-c'
    - |    
        kubectl apply -f templates/cluster.yml
        echo "Customer GKE cluster provisioned"
      
timeout: 1000s     
options:
  logging: CLOUD_LOGGING_ONLY
  
# availableSecrets:
#   secretManager:
#   - versionName: projects/$_PROJECT_ID/secrets/mySecret/versions/latest
#     env: 'MYSECRET'

        
